[[main]]
name = "Home"
url = ""
weight = 10

[[main]]
name = "📥Download"
url = "download"
weight = 20
title = "Download"


[[main]]
identifier = "Features"
name = "🚀Features"
url = "features"
weight = 50

[[main]]
identifier = "Plugins"
name = "🧰Plugins"
url = "plugins"
weight = 52

[[main]]
identifier = "Knowledge"
name = "🎬How-To"
url = "knowledge"
weight = 55


[[main]]
identifier = "News"
name = "📰News"
url = "news"
weight = 57

[[main]]
identifier = "Donate"
name = "⚡Support"
url = "donate"
weight = 60


[[social]]
  name = "GitHub"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-github'><use href='/images/feather/feather-sprite.svg#github'/></svg>"
  url = "https://github.com/andreasgriffin/bitcoin-safe"
  weight = 10
  title = "Visit the GitHub project"



[[social]]
  name = "Substr"
  pre = "<img src='/icons/substr.svg' alt='Nostr' class='feather feather-github' />"
  url = "https://substr.network/s/bitcoin-safe"
  weight = 11
  title = "Substr Community"

# [[social]]
#   name = "Email"
#   pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-email'><use href='images/feather/feather-sprite.svg#email'/></svg>"
#   url = "<a href='Contact@Bitcoin-Safe.org'>Example mailto link</a>"
#   weight = 10
#   title = "Mail me"


[[social]]
  name = "Nostr"
  pre = "<img src='/icons/nostr-logo-outline.svg' alt='Nostr' class='feather feather-github' />"
  url = "https://nostr.com/npub1g9uhysae68vhvwwqel8v9enr9mg43rn4tpurs6a9g4jsrw6nl7lsplhs9v"
  weight = 20
  title = "Nostr Profile"



[[social]]
  name = "Twitter"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-twitter'><use href='/images/feather/feather-sprite.svg#twitter'/></svg>"
  url = "https://x.com/BitcoinSafeOrg"
  weight = 21
  title = "Contact on Twitter"



[[social]]
  name = "Youtube"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-youtube'><use href='/images/feather/feather-sprite.svg#youtube'/></svg>"
  url = "https://www.youtube.com/@BitcoinSafeOrg"
  weight = 20
  title = "Channel on Youtube"
